### ISSUE TITLE
schedule fails with an exception and no message

### ISSUE THREAD

**Issue by terrasea** [dart-lang/scheduled_test#1]
When I ran a test using this package using something like

import 'package:scheduled_test/scheduled_test.dart';
import 'package:unittest/html_config.dart';

main() {
  useHtmlConfiguration(true);

  group('yeah', () {
    test('fail', () {
      schedule(() {
          expect(true, true);
      });
    });
  });
}

It fails with the following message

Breaking on exception: 

and nothing more

The same thing happens if I do something like

main() {
  useHtmlConfiguration(true);

  group('yeah', () {
    test('fail', () {
      schedule(() {
        return new Future.microtask(() =>
          expect(true, true)
          );
      });
    });
  });
}

What I expect is for the test to run and in this case pass, not through an exception.

Here is my pubspec.yaml file contents

name: simple
version: 0.0.1
description: Simple test
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
dev_dependencies:
  scheduled_test: any

And my Dart version info

Dart Editor version 1.8.3.release (STABLE)
Dart SDK version 1.8.3

**Comment by terrasea** [comment]
As an update, this maybe a bug specific to one of my laptops OS setup, as the above works perfectly fine on my other laptop.  I'll close this and in the mean time try to figure out what the difference is, that causes this to happen on the offending computer.  I'll update this when I figure out what the difference is, and it maybe a bug that needs to be filed with dart itself.  Feel free to reopen if you feel I'm incorrect in closing it.

**Comment by terrasea** [comment]
Turns out to be a config problem, as I solved it by deleting both ~/.dartEditor and ~/.dartium directories.  Which one was the culprit I don't know.  I am leaving this comment just in case someone else has the same problem.

**Comment by munificent** [comment]
Bizarre, but thanks for leaving some details here!
