### ISSUE TITLE
Tasks scheduled in setUpAll complete before tests would run

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/scheduled_test#28]
My expectation when using setUpAll is that it will allow me to schedule tasks that are to be ran once for a group.

What actually happens is that setUpAll's body is invoked before tests' would be added to the task queue and the queue completes before the tests would run.

Works the way I `expect` it:

```dart
import 'package:scheduled_test/scheduled_test.dart';

main() {
  setUp(() {
    schedule(() {
      print('Ren scheduled...');
    }, 'printing thing');
  });

  test('', () {
    print('Current tasks:\n${currentSchedule.currentQueue.generateTree()}\n');
    expect(currentSchedule.currentQueue.contents.length, greaterThan(0));
  });
}
```
Output:

```
>pub run test test\sample_project_test.dart
00:00 +0:
Current tasks:
* printing thing

Ren scheduled...
00:00 +1: All tests passed!
```

**Does not work as I expect it:**

```dart
import 'package:scheduled_test/scheduled_test.dart';

main() {
  setUpAll(() { // Please note that setUp became setUpAll
    schedule(() {
      print('Ren scheduled...');
    }, 'printing thing');
  });

  test('', () {
    print('Current tasks:\n${currentSchedule.currentQueue.generateTree()}\n');
    expect(currentSchedule.currentQueue.contents.length, greaterThan(0));
  });
}
```

Output:

```
>pub run test test\sample_project_test.dart
00:00 +0: (setUpAll)
Ren scheduled...
00:00 +0:
Current tasks:


00:00 +0 -1:
  ScheduleError:
  | Expected: a value greater than <0>
  |   Actual: <0>
  |    Which: is not a value greater than <0>

  Stack chain:
  | package:test/src/frontend/expect.dart 88:30       fail
  | package:test/src/frontend/expect.dart 83:3        expect
  | test\sample_project_test.dart 29:5                main.<fn>
  | package:scheduled_test/scheduled_test.dart 69:27  test.<fn>.<fn>
  | package:scheduled_test/src/schedule.dart 83:16    Schedule.run.<fn>.<fn>
  | dart:async                                        runZoned
  | package:scheduled_test/src/schedule.dart 81:14    Schedule.run.<fn>
  | package:test/src/backend/invoker.dart 200:17      Invoker.waitForOutstandingCallbacks.<fn>.<fn>.<async>

  Error detected when waiting for out-of-band callbacks in queue "tasks".

00:00 +0 -1: Some tests failed.
```

Am I missing something, is my expectation wrong?

**Comment by nex3** [comment]
`scheduled_test` doesn't do any special wrapping of `setUpAll()`, and it's not likely to—this package is on the road to being deprecated in favor of just using `async`/`await` directly.

**Comment by daniel-v** [comment]
@nex3 In that case I would recommend removing this very misleading comment: 

```
/// This has the same semantics as [test_pkg.setUpAll].
```

https://github.com/dart-lang/scheduled_test/blob/a413fe4097e12d170169bbcecc8074f80329b72c/lib/scheduled_test.dart#L115

From where I sit, it's simply not true and caused me to expect something to happen that will never happen - as it turns out.

As for the deprecation, will the entire package just be abandoned or will some of it survive, such as Descriptors and ScheduledProcess? I find those helpful.

Also, if I may, in the future, should such deprecation decisions be made in a dart-lang package, I would appreciate very much a notice in the readme file.

**Comment by nex3** [comment]
> In that case I would recommend removing this very misleading comment: 
> 
> ```
> /// This has the same semantics as [test_pkg.setUpAll].
> ```
> 
> https://github.com/dart-lang/scheduled_test/blob/a413fe4097e12d170169bbcecc8074f80329b72c/lib/scheduled_test.dart#L115
> 
> From where I sit, it's simply not true and caused me to expect something to happen that will never happen - as it turns out.

That comment is accurate. The `setUpAll()` block is executed once, before any tests in the group are executed. It just doesn't interact with their schedules—and in fact, I'm not sure how it could do so while maintaining the `test` semantics.

> As for the deprecation, will the entire package just be abandoned or will some of it survive, such as Descriptors and ScheduledProcess? I find those helpful.

Definitely! I've already factored out [`test_descriptor`](https://github.com/dart-lang/test_descriptor), and I'm working on factoring out `scheduled_stream` and `scheduled_process` as well.

> Also, if I may, in the future, should such deprecation decisions be made in a dart-lang package, I would appreciate very much a notice in the readme file.

I don't want to officially mark the package as deprecated until downstream users can do something to remove their dependency, which means providing usable alternatives for all the functionality in the package. We're not there yet with `scheduled_test`.
