### ISSUE TITLE
Advantages of `schedule` over await?

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/scheduled_test#3]
Now that we have `await`, at first glance it's unclear to me what the advantages of `schedule` over await are.  Why wouldn't I  just write the example in the README as:

``` dart
  test('writing to a file and reading it back should work', () async {
    var file = new File("output.txt");
    await file.writeAsString("contents");
    expect(await file.readAsString(), equals("contents"));
  });
```

**Comment by nex3** [comment]
There's still something to be said for not having to write `await` all over the place, but it's certainly less relevant now than it was when `scheduled_test` was first designed. But avoiding unwieldy future chains was only ever part of the motivation; having explicit tasks with descriptions allows the test framework to put together a textual representation of the current state of the test, which can be very helpful when debugging complex asynchrony.

At some point I may move some of the ancillary stuff in here out into other packages with more Future-focused APIs, but I think `scheduled_test` still has its place.
